[keyboard]
name = "Totem"
product_name = "Totem"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "nrf52840"

[storage]
# "true" will reset stored layout and BT connection
#clear_storage = true

[layout]
rows = 4
cols = 10
layers = 1
keymap = [
    [
        ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
        ["A", "S", "D", "F", "G", "H", "J", "K", "L", ";"],
        ["Z", "X", "C", "V", "B", "N", "M", ",", ".", "/"],
        ["esc", "No", "bspc", "spc", "l_shift",
            "r_gui", "ent", "Tab", "No", "r_ctrl"]
    ],
]

[ble]
enabled = true

[behavior]
tap_hold = { enable_hrm = true }

[split]
connection = "ble"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0

[split.central.matrix]
input_pins = ["P0_02", "P0_03", "P0_28", "P0_29"]
output_pins = ["P0_04", "P0_05", "P1_15", "P1_14", "P1_13"]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5

[split.peripheral.matrix]
input_pins = ["P0_02", "P0_03", "P0_28", "P0_29"]
output_pins = ["P1_13", "P1_14", "P1_15", "P0_05", "P0_04"]
